on:
  workflow_dispatch:

env:
  GOOS: android

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: apt deps
      run: apt update && make linux-dep
    - name: ffmpeg
      run: make ffmpeg-android
    - name: build
      run: |
        make edit-android
        make build-android
    - name: bundle
      run: make module.tar.gz
    - uses: actions/upload-artifact@v3
